// Package domain defines the stable domain types shared across the
// rammed-earth roof-beam clearance quality workflow. These types mirror the
// persisted data model described in PROJECT_SPEC.md and are intentionally
// free of behaviour so they can be exchanged across package boundaries
// without import cycles.
package domain

// TaskID identifies a locked task. It is opaque and generated by the server.
type TaskID string

// Generation is a monotonically increasing task generation. Rebuilds open a
// new generation; late receipts from older generations are rejected.
type Generation int64

// LogicalTime is a monotonic, total-ordered clock value. Every state advance
// carries a logical time and regressions are rejected before write.
type LogicalTime int64

// Digest is the immutable design digest produced when a task is locked.
type Digest string

// OperationID is a client-supplied idempotency key scoped to a task.
type OperationID string

// LeaseToken identifies a held exclusive resource lease.
type LeaseToken string

// Direction is the locked compaction direction along a wall segment.
type Direction string

const (
	DirectionRising  Direction = "rising" // low wall-end to high wall-end
	DirectionFalling Direction = "falling"
)

// TaskStatus is the coarse lifecycle state of a locked task.
type TaskStatus string

const (
	TaskActive    TaskStatus = "active"
	TaskIsolated  TaskStatus = "isolated"
	TaskCleared   TaskStatus = "cleared"
	TaskCancelled TaskStatus = "cancelled"
)

// LockedTask is the immutable-at-lock task header (data model item 1).
type LockedTask struct {
	ID          TaskID
	Area        string
	Digest      Digest
	Generation  Generation
	Direction   Direction
	Clock       LogicalTime
	Status      TaskStatus
	RuleVersion int
}

// Rect is an integer-millimetre axis-aligned rectangle.
type Rect struct {
	X int64 `json:"x"`
	Y int64 `json:"y"`
	W int64 `json:"w"`
	H int64 `json:"h"`
}

// Opening is a door/window opening excluded from the wall entity.
type Opening struct {
	Name string `json:"name"`
	Rect Rect   `json:"rect"`
}

// Tie is a tie bar with its forbidden protection zone.
type Tie struct {
	Name    string `json:"name"`
	Rect    Rect   `json:"rect"`
	Reserve Rect   `json:"reserve"` // protection zone that compaction cells must avoid
}

// Layer divides the wall into horizontal layers.
type Layer struct {
	Number int  `json:"number"`
	Rect   Rect `json:"rect"`
}

// Cell is one compaction unit within a layer, appended as a continuous prefix.
type Cell struct {
	Layer int  `json:"layer"`
	Seq   int  `json:"seq"` // unit sequence within the layer, 0-based
	Rect  Rect `json:"rect"`
}

// WallGeometry captures the full locked wall geometry (data model item 2).
type WallGeometry struct {
	Wall        Rect         `json:"wall"`
	Openings    []Opening    `json:"openings"`
	Ties        []Tie        `json:"ties"`
	FormTies    []Rect       `json:"form_ties"`
	Layers      []Layer      `json:"layers"`
	Cells       []Cell       `json:"cells"`
	Grid        []Rect       `json:"grid"`         // inspection measurement grid
	PressureAdj [][2]CellRef `json:"pressure_adj"` // vertical bearing adjacency edges
}

// CellRef addresses a compaction cell deterministically.
type CellRef struct {
	Layer int `json:"layer"`
	Seq   int `json:"seq"`
}

// MaterialBatch is a source/sieving batch of a component (data model item 3).
type MaterialBatch struct {
	ID        string        `json:"id"`
	Component ComponentKind `json:"component"`
	Source    string        `json:"source"`
	BalanceG  int64         `json:"balance_g"` // integer grams remaining
}

// ComponentKind enumerates the conserved material components.
type ComponentKind string

const (
	ComponentRawEarth   ComponentKind = "raw_earth"
	ComponentGravel     ComponentKind = "gravel"
	ComponentStabilizer ComponentKind = "stabilizer"
	ComponentWater      ComponentKind = "water"
	ComponentMix        ComponentKind = "mix"
	ComponentSample     ComponentKind = "sample"
	ComponentRecycle    ComponentKind = "recycle"
	ComponentInWall     ComponentKind = "in_wall"
	ComponentWaste      ComponentKind = "waste"
)

// MixPan is one non-mergeable batch of mixed material (data model item 3).
type MixPan struct {
	ID             string
	PanSeq         int
	MaterialGen    Generation
	MadeAt         LogicalTime
	ExpiresAt      LogicalTime
	Recipe         Recipe
	TargetMoisture int64 // fixed-point, scale Rules.FixedScale
}

// Recipe is the locked integer-gram mix formula.
type Recipe struct {
	RawEarthG   int64 `json:"raw_earth_g"`
	GravelG     int64 `json:"gravel_g"`
	StabilizerG int64 `json:"stabilizer_g"`
	WaterG      int64 `json:"water_g"`
}

// LedgerSide is the debit/credit side of a mass ledger entry.
type LedgerSide string

const (
	SideDebit  LedgerSide = "debit"
	SideCredit LedgerSide = "credit"
)

// MassLedgerEntry is one double-entry mass transaction line (data model item 4).
type MassLedgerEntry struct {
	TxID    string
	Account ComponentKind
	BatchID string
	PanSeq  int
	Gen     Generation
	Side    LedgerSide
	AmountG int64
	Reason  string
	At      LogicalTime
}

// ResourceKind enumerates the exclusively leased resources.
type ResourceKind string

const (
	ResourceMixer         ResourceKind = "mixer"
	ResourceFormArea      ResourceKind = "form_area"
	ResourceRammer        ResourceKind = "rammer"
	ResourceMoistureMeter ResourceKind = "moisture_meter"
	ResourceScanChannel   ResourceKind = "scan_channel"
)

// LeaseStatus is the lifecycle state of a resource lease.
type LeaseStatus string

const (
	LeaseActive   LeaseStatus = "active"
	LeaseExpired  LeaseStatus = "expired"
	LeaseReleased LeaseStatus = "released"
)

// ResourceLease is a limited mutual-exclusion lease (data model item 5).
type ResourceLease struct {
	Kind       ResourceKind
	ResourceID string
	HolderOp   OperationID
	Token      LeaseToken
	AcquiredAt LogicalTime
	ExpiresAt  LogicalTime
	Status     LeaseStatus
	ReclaimVer int64
}

// ProcessKind enumerates the ordered compaction/evidence process steps.
type ProcessKind string

const (
	ProcessSieving      ProcessKind = "sieving"
	ProcessConditioning ProcessKind = "conditioning"
	ProcessMixing       ProcessKind = "mixing"
	ProcessFormAccept   ProcessKind = "form_acceptance"
	ProcessPlacing      ProcessKind = "placing"
	ProcessCompaction   ProcessKind = "compaction"
	ProcessLevelling    ProcessKind = "levelling"
	ProcessTieEmbed     ProcessKind = "tie_embed"
	ProcessCuring       ProcessKind = "curing"
)

// EvidenceEvent is the immutable append-only evidence record for the
// compaction lattice (data model item 6). Each event captures one process
// step — placing, a compaction pass, levelling, tie embedding, curing — with
// its layer/cell/pass coordinates, logical time, actor and fixed-point value.
type EvidenceEvent struct {
	ID         string
	Wall       string
	Layer      int
	Seq        int
	Gen        Generation
	Process    ProcessKind
	Pass       int
	PanSeq     int
	At         LogicalTime
	Actor      string
	ValueFixed int64
	Digest     Digest
	Valid      bool
}

// InstrumentKind enumerates the scriptable measurement instruments.
type InstrumentKind string

const (
	InstrumentScale      InstrumentKind = "scale"
	InstrumentMoisture   InstrumentKind = "moisture_meter"
	InstrumentRamCounter InstrumentKind = "ram_counter"
	InstrumentScanner    InstrumentKind = "scanner"
	InstrumentPress      InstrumentKind = "press"
)

// CallStatus is the lifecycle of a scripted instrument call.
type CallStatus string

const (
	CallPending   CallStatus = "pending"
	CallSucceeded CallStatus = "succeeded"
	CallFailed    CallStatus = "failed"
)

// InstrumentCall is a persistent instrument request (data model item 7).
type InstrumentCall struct {
	ID          string
	Instrument  InstrumentKind
	InputDigest Digest
	At          LogicalTime
	Attempts    int
	MaxAttempts int
	Status      CallStatus
	FaultCode   string
	RawResponse Digest
	NextRetryAt LogicalTime
}

// FindingKind enumerates the detectable quality anomalies.
type FindingKind string

const (
	FindingLowDensity  FindingKind = "low_density"
	FindingMoistureOut FindingKind = "moisture_out_of_range"
	FindingColdJoint   FindingKind = "cold_joint"
	FindingLayerCrack  FindingKind = "layer_crack"
	FindingTieOffset   FindingKind = "tie_offset"
	FindingLowShear    FindingKind = "low_shear"
	FindingErosion     FindingKind = "erosion_over_limit"
)

// InspectionFinding is a threshold verdict on a measured point (data model item 8).
type InspectionFinding struct {
	ID             string
	Wall           string
	Kind           FindingKind
	Point          string // measurement point or contact face
	Layer          int    // origin cell layer (for rebuild propagation)
	Seq            int    // origin cell sequence (for rebuild propagation)
	ThresholdFixed int64
	MeasuredFixed  int64
	At             LogicalTime
}

// RebuildPlan is the unique rebuild set propagation result (data model item 8).
type RebuildPlan struct {
	ID           string
	Wall         string
	SetDigest    Digest
	OldGen       Generation
	NewGen       Generation
	MaterialPath string
	Isolation    string
	Complete     bool
}

// Review is one independent qualified-person review (data model item 9).
type Review struct {
	ID             string
	Wall           string
	Reviewer       string
	Qualified      bool
	Conclusion     string
	EvidenceDigest Digest
	At             LogicalTime
}

// VerdictKind enumerates the terminal single-write verdicts.
type VerdictKind string

const (
	VerdictClear   VerdictKind = "clearance"
	VerdictIsolate VerdictKind = "isolation"
	VerdictCancel  VerdictKind = "cancel"
)

// FinalVerdict is the unique terminal decision (data model item 9).
type FinalVerdict struct {
	ID         string
	Wall       string
	Kind       VerdictKind
	Credential string
	WriteVer   int64
	At         LogicalTime
}

// IdempotencyRecord replays a canonical request result across restarts
// (data model item 10).
type IdempotencyRecord struct {
	Scope          string
	OperationID    OperationID
	RequestDigest  Digest
	ResultDigest   Digest
	HTTPStatus     int
	ResponseDigest Digest
}

// Thresholds are the fixed-point quality acceptance limits locked with the
// task. All values use the rules.FixedScale factor where they are ratios or
// densities; the compaction ratio is a permille (0..1000) ratio.
type Thresholds struct {
	MinDryDensity int64 `json:"min_dry_density"`
	MaxDryDensity int64 `json:"max_dry_density"`
	MinCompaction int64 `json:"min_compaction"`
	MinMoisture   int64 `json:"min_moisture"`
	MaxMoisture   int64 `json:"max_moisture"`
	MinShear      int64 `json:"min_shear"`
	MaxErosion    int64 `json:"max_erosion"`
	MaxDeviation  int64 `json:"max_deviation"`
}

// CompactionProgram is the locked ramming program: loose-lift thickness, pass
// and blow counts, and the rammer geometry used to compute compactive energy.
type CompactionProgram struct {
	LooseThickness int64 `json:"loose_thickness"` // mm
	PassesPerCell  int   `json:"passes_per_cell"`
	BlowsPerPass   int   `json:"blows_per_pass"`
	RammerWeightG  int64 `json:"rammer_weight_g"` // grams
	FallHeightMM   int64 `json:"fall_height_mm"`
}

// CuringSchedule is the locked humidity-equilibration curing timeline.
type CuringSchedule struct {
	HoursPerLayer int `json:"hours_per_layer"`
	MinHours      int `json:"min_hours"`
}

// MixPlan is the locked mix-pan plan. Each pan has a fixed size and a usable
// logical-time window; pans are never merged (domain rule 4).
type MixPlan struct {
	PanCount    int   `json:"pan_count"`
	PanSizeG    int64 `json:"pan_size_g"`
	UsableUnits int64 `json:"usable_units"` // usable window in logical-time units
}

// Specimen is a locked test-specimen mapping onto a measured point.
type Specimen struct {
	ID    string `json:"id"`
	Point string `json:"point"`
}

// TaskSpec is the full immutable design submitted at lock time. Its canonical
// serialization is hashed into the design digest (data model items 1 and 2,
// acceptance 1).
type TaskSpec struct {
	Area           string            `json:"area"`
	Direction      Direction         `json:"direction"`
	Geometry       WallGeometry      `json:"geometry"`
	Batches        []MaterialBatch   `json:"batches"`
	Recipe         Recipe            `json:"recipe"`
	TargetMoisture int64             `json:"target_moisture"`
	Program        CompactionProgram `json:"program"`
	Thresholds     Thresholds        `json:"thresholds"`
	Curing         CuringSchedule    `json:"curing"`
	MixPlan        MixPlan           `json:"mix_plan"`
	Specimens      []Specimen        `json:"specimens"`
}
